name: infrastructure
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
  domain:
    path: ../domain
  cloud_firestore: ^4.14.0

dev_dependencies:
  lints: ^3.0.0
