name: infrastructure
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
  domain:
    path: ../domain
  cloud_firestore: ^4.14.0
  get_it: ^7.6.7
  injectable: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  lints: ^3.0.0
